/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkHoursRouteImport } from './routes/work-hours'
import { Route as IndexRouteImport } from './routes/index'

const WorkHoursRoute = WorkHoursRouteImport.update({
  id: '/work-hours',
  path: '/work-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work-hours': typeof WorkHoursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work-hours': typeof WorkHoursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work-hours': typeof WorkHoursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work-hours'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work-hours'
  id: '__root__' | '/' | '/work-hours'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkHoursRoute: typeof WorkHoursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-hours': {
      id: '/work-hours'
      path: '/work-hours'
      fullPath: '/work-hours'
      preLoaderRoute: typeof WorkHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkHoursRoute: WorkHoursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
